/**
 * Display names for FIFA association codes (ENG → England, not GBR → United Kingdom).
 * Storage stays as three-letter codes; this is UI-only.
 */
const FOOTBALL_COUNTRY_NAMES: Record<string, string> = {
  // UEFA
  ALB: 'Albania',
  AND: 'Andorra',
  ARM: 'Armenia',
  AUT: 'Austria',
  AZE: 'Azerbaijan',
  BEL: 'Belgium',
  BIH: 'Bosnia and Herzegovina',
  BLR: 'Belarus',
  BUL: 'Bulgaria',
  CRO: 'Croatia',
  CYP: 'Cyprus',
  CZE: 'Czechia',
  DEN: 'Denmark',
  ENG: 'England',
  ESP: 'Spain',
  EST: 'Estonia',
  FAR: 'Faroe Islands',
  FIN: 'Finland',
  FRA: 'France',
  GEO: 'Georgia',
  GER: 'Germany',
  GIB: 'Gibraltar',
  GRE: 'Greece',
  HUN: 'Hungary',
  IRL: 'Republic of Ireland',
  ISL: 'Iceland',
  ISR: 'Israel',
  ITA: 'Italy',
  KAZ: 'Kazakhstan',
  KOS: 'Kosovo',
  LVA: 'Latvia',
  LIE: 'Liechtenstein',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',
  MDA: 'Moldova',
  MKD: 'North Macedonia',
  MLT: 'Malta',
  MNE: 'Montenegro',
  NED: 'Netherlands',
  NIR: 'Northern Ireland',
  NOR: 'Norway',
  POL: 'Poland',
  POR: 'Portugal',
  ROU: 'Romania',
  RUS: 'Russia',
  SCO: 'Scotland',
  SMR: 'San Marino',
  SRB: 'Serbia',
  SUI: 'Switzerland',
  SVK: 'Slovakia',
  SVN: 'Slovenia',
  SWE: 'Sweden',
  TUR: 'Türkiye',
  UKR: 'Ukraine',
  WAL: 'Wales',
  // CONMEBOL
  ARG: 'Argentina',
  BOL: 'Bolivia',
  BRA: 'Brazil',
  CHI: 'Chile',
  COL: 'Colombia',
  ECU: 'Ecuador',
  PAR: 'Paraguay',
  PER: 'Peru',
  URU: 'Uruguay',
  VEN: 'Venezuela',
  // CONCACAF (common)
  CAN: 'Canada',
  CRC: 'Costa Rica',
  CUB: 'Cuba',
  JAM: 'Jamaica',
  MEX: 'Mexico',
  PAN: 'Panama',
  USA: 'United States',
  // CAF (common)
  ALG: 'Algeria',
  ANG: 'Angola',
  CIV: "Côte d'Ivoire",
  CMR: 'Cameroon',
  COD: 'DR Congo',
  CGO: 'Congo',
  EGY: 'Egypt',
  GHA: 'Ghana',
  GUI: 'Guinea',
  MAR: 'Morocco',
  MLI: 'Mali',
  NGA: 'Nigeria',
  RSA: 'South Africa',
  SEN: 'Senegal',
  TUN: 'Tunisia',
  // AFC / OFC (common)
  AUS: 'Australia',
  CHN: 'China',
  IRN: 'Iran',
  IRQ: 'Iraq',
  JPN: 'Japan',
  KOR: 'South Korea',
  KSA: 'Saudi Arabia',
  QAT: 'Qatar',
  UAE: 'United Arab Emirates',
  UZB: 'Uzbekistan',
  NZL: 'New Zealand',
}

/** Resolve a FIFA association code to a readable country/association name. */
export function formatFootballCountry(code: string | null | undefined): string {
  if (!code) {
    return '—'
  }
  const normalized = code.trim().toUpperCase()
  return FOOTBALL_COUNTRY_NAMES[normalized] ?? normalized
}
